Simple kill-signall message acceptor for [[http://www.sbcl.org/][sbcl]].

* The scope
A simple and reliable way to send messages to LISP services.

* Prerequisites
Although this code is quite mature, [[https://github.com/chalaev/cl-simple-logger][simple-log]] package is needed for debugging, so =quicklisp= should be able to find its files.

For example, I have =quicklisp= installed in =~/quicklisp/= so [[https://github.com/chalaev/cl-simple-logger][simple-log]] is available in =~/quicklisp/local-projects/simple-log/=.

* Quick start – usage example
=make= compiles the binary =example.bin= and launches it in background.
It is a server that will "listen" for =kill= signals for a few seconds.

LISP services may register one or more ~hooks~ using =(sh:register sdir func)=,
where =dir= is the name of the lock (sub)directory.

The shell script [[file:generated/tell][tell]] is a client that
1. creates lock directory to let other clients know that they should not interfere until the current conversation with the server is over,
2. saves a message in a file "by", and
3. sends =kill= signal to the server thus letting it know that the message is ready to be read.

After receiving the =kill= signal, the LISP code checks every hook it has.
A hook is a =cons=; its =car= is the sub-directory name =sdir=.
If this sub-directory exists, the hook is activated, and its =cdr= (which is a function)
is called with a string argument read from the file named "by" residing in =sdir=.

After that the file "by" is erased by the LISP code.
In this way the sender is notified that the message has been received,
and now the sender must delete the sub-directory =sdir= in order to allow others to send messages to LISP code.

* Files
1. [[file:signal-handler.org][signal-handler.org]] is the main file containing most of the code with comments.
2. [[file:Makefile][Makefile]] compiles [[file:generated/example.lisp][generated/example.lisp]] into ~generated/example.bin~ and launches it.
3. Other files in [[file:generated][generated/]] can be produced by ~emacs~ from [[file:signal-handler.org][signal-handler.org]] using either =make= or =M-x org-babel-tangle=.
4. [[file:make.org][make.org]] shows the log messages displayed by =make= command.
5. [[file:helpers/][helpers/*]] assist compilation.

* Motivation
[[https://github.com/death/dbus][dbus]] might have many fancy features, but on my computer =(ql:quickload :dbus)= downloads 55 other packages to satisfy [[https://github.com/death/dbus][dbus]]'es requirements,
which is much more than I need to satisfy my modest needs: I just need simple text message exchange between ~sbcl~ and other programs (including shell scripts).

* License
This code is released under [[https://mit-license.org/][MIT license]].

* Support
You can support this project by sending
1. comments/questions to [[mailto:oleg@chalaev.com][oleg@chalaev.com]] and
2. donations via [[https://liberapay.com/shalaev/donate][liberapay]] or [[https://www.paypal.com/paypalme/chalaev][paypal]].
